name: trigger-circleci
on:
 push:
    branches:
      - main
      
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI
        run: >
          curl -X POST --location "https://circleci.com/api/v2/project/gh/nikhiltevaera/circleci-demo/pipeline" \
            -H "Content-Type: application/json" \
            -H "Circle-Token: $CCI_TOKEN" \
            -d '{
                  "branch": "'$BRANCH'",
                  "parameters": {"GHA_Actor":"nikhiltevaera","GHA_Action":"dev-release","GHA_Event":"push","GHA_Meta":"custom meta-tags"}
                }'
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
          BRANCH: main
    
