name: CircleCI
on:
 push:
    branches:
      - main
      
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: CircleCI
        id: dev-release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
    