name: CircleCI
on:
 push:
    branches:
      - main
      
jobs:
  trigger-circleci:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI
        id: main-release
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
    