name: trigger-circleci
on:
 push:
    branches:
      - main
      
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI
        id: dev-release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: "custom meta-tags"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
          API_URL: https://circleci.com/api/v1.1
    