name: CircleCI
on:
 push:
    branches:
      - main
      
jobs:
  trigger-circleci:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI
        id: main-release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
    