name: CircleCI
on:
 push:
    branches:
      - main
      
jobs:
  echo-job: 
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Echo CCI Token
        run: |
          echo "CCI_TOKEN: ${{ secrets.CCI_TOKEN }}"
  trigger-circleci:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI
        id: main-release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
    